//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CokYasarSapEntegrasyon.sapPuantajService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZCYHR_WS_001", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_WS_001 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZCYHR_FG003_003OperationCompleted;
        
        private System.Threading.SendOrPostCallback ZCYHR_FG003_002OperationCompleted;
        
        private System.Threading.SendOrPostCallback ZCYHR_FG003_001OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZCYHR_WS_001() {
            this.Url = global::CokYasarSapEntegrasyon.Properties.Settings.Default.CokYasarSapEntegrasyon_sapPuantajService_ZCYHR_WS_001;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZCYHR_FG003_003CompletedEventHandler ZCYHR_FG003_003Completed;
        
        /// <remarks/>
        public event ZCYHR_FG003_002CompletedEventHandler ZCYHR_FG003_002Completed;
        
        /// <remarks/>
        public event ZCYHR_FG003_001CompletedEventHandler ZCYHR_FG003_001Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZCYHR_WS001:ZCYHR_FG003_003Request", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZCYHR_FG003_003Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZCYHR_FG003_003Response ZCYHR_FG003_003([System.Xml.Serialization.XmlElementAttribute("ZCYHR_FG003_003", Namespace="urn:sap-com:document:sap:rfc:functions")] ZCYHR_FG003_003 ZCYHR_FG003_0031) {
            object[] results = this.Invoke("ZCYHR_FG003_003", new object[] {
                        ZCYHR_FG003_0031});
            return ((ZCYHR_FG003_003Response)(results[0]));
        }
        
        /// <remarks/>
        public void ZCYHR_FG003_003Async(ZCYHR_FG003_003 ZCYHR_FG003_0031) {
            this.ZCYHR_FG003_003Async(ZCYHR_FG003_0031, null);
        }
        
        /// <remarks/>
        public void ZCYHR_FG003_003Async(ZCYHR_FG003_003 ZCYHR_FG003_0031, object userState) {
            if ((this.ZCYHR_FG003_003OperationCompleted == null)) {
                this.ZCYHR_FG003_003OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZCYHR_FG003_003OperationCompleted);
            }
            this.InvokeAsync("ZCYHR_FG003_003", new object[] {
                        ZCYHR_FG003_0031}, this.ZCYHR_FG003_003OperationCompleted, userState);
        }
        
        private void OnZCYHR_FG003_003OperationCompleted(object arg) {
            if ((this.ZCYHR_FG003_003Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZCYHR_FG003_003Completed(this, new ZCYHR_FG003_003CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZCYHR_WS001:ZCYHR_FG003_002Request", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZCYHR_FG003_002Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZCYHR_FG003_002Response ZCYHR_FG003_002([System.Xml.Serialization.XmlElementAttribute("ZCYHR_FG003_002", Namespace="urn:sap-com:document:sap:rfc:functions")] ZCYHR_FG003_002 ZCYHR_FG003_0021) {
            object[] results = this.Invoke("ZCYHR_FG003_002", new object[] {
                        ZCYHR_FG003_0021});
            return ((ZCYHR_FG003_002Response)(results[0]));
        }
        
        /// <remarks/>
        public void ZCYHR_FG003_002Async(ZCYHR_FG003_002 ZCYHR_FG003_0021) {
            this.ZCYHR_FG003_002Async(ZCYHR_FG003_0021, null);
        }
        
        /// <remarks/>
        public void ZCYHR_FG003_002Async(ZCYHR_FG003_002 ZCYHR_FG003_0021, object userState) {
            if ((this.ZCYHR_FG003_002OperationCompleted == null)) {
                this.ZCYHR_FG003_002OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZCYHR_FG003_002OperationCompleted);
            }
            this.InvokeAsync("ZCYHR_FG003_002", new object[] {
                        ZCYHR_FG003_0021}, this.ZCYHR_FG003_002OperationCompleted, userState);
        }
        
        private void OnZCYHR_FG003_002OperationCompleted(object arg) {
            if ((this.ZCYHR_FG003_002Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZCYHR_FG003_002Completed(this, new ZCYHR_FG003_002CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZCYHR_WS001:ZCYHR_FG003_001Request", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZCYHR_FG003_001Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZCYHR_FG003_001Response ZCYHR_FG003_001([System.Xml.Serialization.XmlElementAttribute("ZCYHR_FG003_001", Namespace="urn:sap-com:document:sap:rfc:functions")] ZCYHR_FG003_001 ZCYHR_FG003_0011) {
            object[] results = this.Invoke("ZCYHR_FG003_001", new object[] {
                        ZCYHR_FG003_0011});
            return ((ZCYHR_FG003_001Response)(results[0]));
        }
        
        /// <remarks/>
        public void ZCYHR_FG003_001Async(ZCYHR_FG003_001 ZCYHR_FG003_0011) {
            this.ZCYHR_FG003_001Async(ZCYHR_FG003_0011, null);
        }
        
        /// <remarks/>
        public void ZCYHR_FG003_001Async(ZCYHR_FG003_001 ZCYHR_FG003_0011, object userState) {
            if ((this.ZCYHR_FG003_001OperationCompleted == null)) {
                this.ZCYHR_FG003_001OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZCYHR_FG003_001OperationCompleted);
            }
            this.InvokeAsync("ZCYHR_FG003_001", new object[] {
                        ZCYHR_FG003_0011}, this.ZCYHR_FG003_001OperationCompleted, userState);
        }
        
        private void OnZCYHR_FG003_001OperationCompleted(object arg) {
            if ((this.ZCYHR_FG003_001Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZCYHR_FG003_001Completed(this, new ZCYHR_FG003_001CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_FG003_003 {
        
        private ZCYHR_S023[] iT_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCYHR_S023[] IT_DATA {
            get {
                return this.iT_DATAField;
            }
            set {
                this.iT_DATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_S023 {
        
        private string pERNRField;
        
        private string dATUMField;
        
        private string tPROGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATUM {
            get {
                return this.dATUMField;
            }
            set {
                this.dATUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TPROG {
            get {
                return this.tPROGField;
            }
            set {
                this.tPROGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_S011 {
        
        private string pERNRField;
        
        private string eNAMEField;
        
        private string aWARTField;
        
        private string aTEXTField;
        
        private string bEGDAField;
        
        private string eNDDAField;
        
        private string bEGUZField;
        
        private string eNDUZField;
        
        private decimal aBWTGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENAME {
            get {
                return this.eNAMEField;
            }
            set {
                this.eNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AWART {
            get {
                return this.aWARTField;
            }
            set {
                this.aWARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATEXT {
            get {
                return this.aTEXTField;
            }
            set {
                this.aTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BEGDA {
            get {
                return this.bEGDAField;
            }
            set {
                this.bEGDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDDA {
            get {
                return this.eNDDAField;
            }
            set {
                this.eNDDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BEGUZ {
            get {
                return this.bEGUZField;
            }
            set {
                this.bEGUZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDUZ {
            get {
                return this.eNDUZField;
            }
            set {
                this.eNDUZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ABWTG {
            get {
                return this.aBWTGField;
            }
            set {
                this.aBWTGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_S014 {
        
        private string mERNIField;
        
        private string pERNRField;
        
        private string vORNAField;
        
        private string nACHNField;
        
        private string gBDATField;
        
        private string gESCHField;
        
        private string gESCH_TXField;
        
        private string bUKRSField;
        
        private string bUTXTField;
        
        private string wERKSField;
        
        private string pBTXTField;
        
        private string bTRTLField;
        
        private string bTEXTField;
        
        private string pERSGField;
        
        private string pERSG_TXField;
        
        private string pERSKField;
        
        private string pTEXTField;
        
        private string oRGEHField;
        
        private string oRGTXField;
        
        private string pLANSField;
        
        private string pLNTXField;
        
        private string sTELLField;
        
        private string sTLTXField;
        
        private string kOSTLField;
        
        private string lTEXTField;
        
        private string hIREDATEField;
        
        private string fIREDATEField;
        
        private string tOPDTField;
        
        private string mASSNField;
        
        private string mASSGField;
        
        private string mGTXTField;
        
        private string yNTSCLField;
        
        private string yNTADField;
        
        private string yNTSCL2Field;
        
        private string yNTAD2Field;
        
        private string yNTSCL3Field;
        
        private string yNTAD3Field;
        
        private string yNTSCL4Field;
        
        private string yNTAD4Field;
        
        private string yNTSCL5Field;
        
        private string yNTAD5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MERNI {
            get {
                return this.mERNIField;
            }
            set {
                this.mERNIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VORNA {
            get {
                return this.vORNAField;
            }
            set {
                this.vORNAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NACHN {
            get {
                return this.nACHNField;
            }
            set {
                this.nACHNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GBDAT {
            get {
                return this.gBDATField;
            }
            set {
                this.gBDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GESCH {
            get {
                return this.gESCHField;
            }
            set {
                this.gESCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GESCH_TX {
            get {
                return this.gESCH_TXField;
            }
            set {
                this.gESCH_TXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUTXT {
            get {
                return this.bUTXTField;
            }
            set {
                this.bUTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PBTXT {
            get {
                return this.pBTXTField;
            }
            set {
                this.pBTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BTRTL {
            get {
                return this.bTRTLField;
            }
            set {
                this.bTRTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BTEXT {
            get {
                return this.bTEXTField;
            }
            set {
                this.bTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERSG {
            get {
                return this.pERSGField;
            }
            set {
                this.pERSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERSG_TX {
            get {
                return this.pERSG_TXField;
            }
            set {
                this.pERSG_TXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERSK {
            get {
                return this.pERSKField;
            }
            set {
                this.pERSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PTEXT {
            get {
                return this.pTEXTField;
            }
            set {
                this.pTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORGEH {
            get {
                return this.oRGEHField;
            }
            set {
                this.oRGEHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORGTX {
            get {
                return this.oRGTXField;
            }
            set {
                this.oRGTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLANS {
            get {
                return this.pLANSField;
            }
            set {
                this.pLANSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PLNTX {
            get {
                return this.pLNTXField;
            }
            set {
                this.pLNTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STELL {
            get {
                return this.sTELLField;
            }
            set {
                this.sTELLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STLTX {
            get {
                return this.sTLTXField;
            }
            set {
                this.sTLTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LTEXT {
            get {
                return this.lTEXTField;
            }
            set {
                this.lTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIREDATE {
            get {
                return this.hIREDATEField;
            }
            set {
                this.hIREDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIREDATE {
            get {
                return this.fIREDATEField;
            }
            set {
                this.fIREDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOPDT {
            get {
                return this.tOPDTField;
            }
            set {
                this.tOPDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MASSN {
            get {
                return this.mASSNField;
            }
            set {
                this.mASSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MASSG {
            get {
                return this.mASSGField;
            }
            set {
                this.mASSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MGTXT {
            get {
                return this.mGTXTField;
            }
            set {
                this.mGTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTSCL {
            get {
                return this.yNTSCLField;
            }
            set {
                this.yNTSCLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTAD {
            get {
                return this.yNTADField;
            }
            set {
                this.yNTADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTSCL2 {
            get {
                return this.yNTSCL2Field;
            }
            set {
                this.yNTSCL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTAD2 {
            get {
                return this.yNTAD2Field;
            }
            set {
                this.yNTAD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTSCL3 {
            get {
                return this.yNTSCL3Field;
            }
            set {
                this.yNTSCL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTAD3 {
            get {
                return this.yNTAD3Field;
            }
            set {
                this.yNTAD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTSCL4 {
            get {
                return this.yNTSCL4Field;
            }
            set {
                this.yNTSCL4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTAD4 {
            get {
                return this.yNTAD4Field;
            }
            set {
                this.yNTAD4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTSCL5 {
            get {
                return this.yNTSCL5Field;
            }
            set {
                this.yNTSCL5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YNTAD5 {
            get {
                return this.yNTAD5Field;
            }
            set {
                this.yNTAD5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_S024 {
        
        private string pERNRField;
        
        private string dATUMField;
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATUM {
            get {
                return this.dATUMField;
            }
            set {
                this.dATUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_FG003_003Response {
        
        private ZCYHR_S024[] eT_MESSAGEField;
        
        private string eV_RETURN_MESSAGEField;
        
        private string eV_RETURN_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCYHR_S024[] ET_MESSAGE {
            get {
                return this.eT_MESSAGEField;
            }
            set {
                this.eT_MESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EV_RETURN_MESSAGE {
            get {
                return this.eV_RETURN_MESSAGEField;
            }
            set {
                this.eV_RETURN_MESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EV_RETURN_TYPE {
            get {
                return this.eV_RETURN_TYPEField;
            }
            set {
                this.eV_RETURN_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_FG003_002 {
        
        private string iV_BTRTLField;
        
        private string iV_BUKRSField;
        
        private string iV_DATUMField;
        
        private string iV_PERNRField;
        
        private string iV_WERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BTRTL {
            get {
                return this.iV_BTRTLField;
            }
            set {
                this.iV_BTRTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BUKRS {
            get {
                return this.iV_BUKRSField;
            }
            set {
                this.iV_BUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_DATUM {
            get {
                return this.iV_DATUMField;
            }
            set {
                this.iV_DATUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_PERNR {
            get {
                return this.iV_PERNRField;
            }
            set {
                this.iV_PERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_WERKS {
            get {
                return this.iV_WERKSField;
            }
            set {
                this.iV_WERKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_FG003_002Response {
        
        private ZCYHR_S014[] eT_OUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCYHR_S014[] ET_OUT {
            get {
                return this.eT_OUTField;
            }
            set {
                this.eT_OUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_FG003_001 {
        
        private string iV_BEGDAField;
        
        private string iV_BTRTLField;
        
        private string iV_ENDDAField;
        
        private string iV_PERNRField;
        
        private string iV_WERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BEGDA {
            get {
                return this.iV_BEGDAField;
            }
            set {
                this.iV_BEGDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_BTRTL {
            get {
                return this.iV_BTRTLField;
            }
            set {
                this.iV_BTRTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_ENDDA {
            get {
                return this.iV_ENDDAField;
            }
            set {
                this.iV_ENDDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_PERNR {
            get {
                return this.iV_PERNRField;
            }
            set {
                this.iV_PERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_WERKS {
            get {
                return this.iV_WERKSField;
            }
            set {
                this.iV_WERKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCYHR_FG003_001Response {
        
        private ZCYHR_S011[] eT_OUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCYHR_S011[] ET_OUT {
            get {
                return this.eT_OUTField;
            }
            set {
                this.eT_OUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZCYHR_FG003_003CompletedEventHandler(object sender, ZCYHR_FG003_003CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZCYHR_FG003_003CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZCYHR_FG003_003CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZCYHR_FG003_003Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZCYHR_FG003_003Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZCYHR_FG003_002CompletedEventHandler(object sender, ZCYHR_FG003_002CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZCYHR_FG003_002CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZCYHR_FG003_002CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZCYHR_FG003_002Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZCYHR_FG003_002Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZCYHR_FG003_001CompletedEventHandler(object sender, ZCYHR_FG003_001CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZCYHR_FG003_001CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZCYHR_FG003_001CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZCYHR_FG003_001Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZCYHR_FG003_001Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591